# Generated by Django 4.2.6 on 2023-10-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pasport_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pasport_seria',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
