# Generated by Django 4.2.6 on 2023-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pasport_seria',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
