# Generated by Django 4.2.6 on 2023-10-13 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/about')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('continuity', models.CharField(max_length=50)),
                ('number_of_people', models.IntegerField()),
                ('course_program', models.TextField()),
                ('offer', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainapp.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), mainapp.services.validate_size_image])),
                ('position', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(blank=True, null=True, upload_to='mainapp/newslatter')),
                ('description', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('NW', 'NEWS'), ('BG', 'BLOG')], default='NW', max_length=2)),
                ('choose', models.BooleanField()),
            ],
            options={
                'verbose_name': 'newslatter',
                'verbose_name_plural': 'newslatters',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image/result')),
                ('time_of_studied', models.DateTimeField()),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('passport', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=250)),
                ('offerta_agreement', models.BooleanField()),
                ('payment_image', models.ImageField(upload_to='mainapp/payment_images')),
                ('transaction_id', models.CharField(max_length=250)),
                ('paid', models.BooleanField()),
                ('bolib_tolash', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserContract',
                'verbose_name_plural': 'UserContracts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usercontract')),
            ],
        ),
    ]
