# Generated by Django 4.2.6 on 2023-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontract',
            name='step',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
