# Generated by Django 4.2.6 on 2023-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_usercontract_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontract',
            name='step',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
