# Generated by Django 4.2.6 on 2023-10-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_usercontract_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontract',
            name='offerta_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
